sudo: required
services:
  - docker

before_install:
  - docker build -t ey0001/docker-react -f Dockerfile.dev .

script:
  #  - docker run ey0001/docker-react npm run test -- --coverage
  - docker run -e CI=true ey0001/docker-react npm run test
