sudo: required
services:
  - docker

before_install:
  - docker build -t ey0001/docker-react -f Dockerfile.dev .

script:
  #  - docker run ey0001/docker-react npm run test -- --coverage
  - docker run -e CI=true ey0001/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-193841948347"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
